stages:
  - build
  - test

before_script:
  - docker network create node-app

build_and_run:
  image: "node:12-alpine"
  stage: build
  script:
    - npm install
    - npm run build
    - npm start &

# execute Ghost Inspector suite
ghost_inspector_test:
  image:
    name: ghostinspector/test-runner-standalone
    entrypoint: [""]
  variables:
    GI_SUITE: 5c1d24568ec4123e847a9ecd
    APP_PORT: node-app:3000
  stage: test
  script:
    - /bin/runghostinspectorsuite
