image:
  name: ghostinspector/test-runner-node
  entrypoint: [""]
variables:
  #GI_API_KEY: $GI_API_KEY
  GI_SUITE: 5c1d24568ec4123e847a9ecd
  #NGROK_TOKEN: $NGROK_TOKEN
  APP_PORT: 3000

before_script:
  - npm install
  - npm run build

# execute Ghost Inspector suite
ghost_inspector_test:
  script:
    - /bin/runghostinspectorsuite server.js
