[[plugins]]
  package = "netlify-plugin-ghost-inspector"

[build]
  environment = { NODE_VERSION = "14.16.0", NPM_FLAGS = "--legacy-peer-deps" }

[context.deploy-preview.processing.images]
  compress = false