name: Test Ghost Inspector

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # sets status to pending (default)
      # - uses: ouzi-dev/commit-status-updater@v1.0.7
      - name: Output Staging Tests
        # id: output_staging_tests
        env:
          API_KEY: ${{ secrets.GI_API_KEY }}
          SUITE_ID: ${{ secrets.GI_SUITE_ID }}
        run: |
          GI_PASSING=$(curl 'https://api.ghostinspector.com/v1/suites/$SUITE_ID/results/?apiKey=$API_KEY&count=1' | jq '.data[0].passing' | tr -d '"')
          echo $GI_PASSING
          if [[ "$GI_PASSING" != "true" ]]; then
            exit 1
          fi
      # # update commit status based on results of above API request
      # - if: always()
      #   uses: ouzi-dev/commit-status-updater@v1.0.7
      #   with:
      #     status: ${{ steps.output_staging_tests.outputs.status }}
      #     url: https://app.ghostinspector.com/suites/${{ env.SUITE_ID }}
      #     description: "this is my status check"
      #     name: "name of my status check"
