name: Test Ghost Inspector

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:12-alpine
      # this will be used by the Ghost Inspector container
      options: --network-alias node-app
    steps:
      # - uses: actions/checkout@v2
      # - name: install, build, and run app
      #   run: |
      #     npm install
      #     npm run build
      #     npm start &
      - name: execute Ghost Inspector suite
        env:
          GI_API_KEY: ${{ secrets.GI_API_KEY }}
          GI_SUITE: ${{ secrets.GI_SUITE }}
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          # this uses the network-alias defined in the container options
          APP_PORT: node-app:3000
        uses: docker://ghostinspector/test-runner-standalone
