name: Test Ghost Inspector

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:12-alpine
    steps:
      - name: Wait for the Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@v1
        id: netlify
        with:
          site_name: "simpixelated"
          max_timeout: 120
      - name: run-ghost-inspector-suite
        uses: DATADEER/run-ghost-inspector-suite-action@v1.2
        with:
          suiteID: ${{ secrets.GI_SUITE }}
          startURL: ${{ steps.netlify.outputs.url }}
          GHOST_INSPECTOR_API_KEY: ${{ secrets.GI_API_KEY }}
