# This is a basic workflow to help you get started with Actions

name: GI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: npm install
      - name: start app
        run: npm start
      - name: execute Ghost Inspector suite
        env:
          GI_API_KEY: ${{ secrets.GI_API_KEY }}
          GI_SUITE: ${{ secrets.GI_SUITE }}
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          APP_PORT: 3000
        run: docker run \
          -e APP_PORT \
          -e GI_API_KEY \
          -e NGROK_TOKEN \
          --network "${{ job.container.network }}" \
          ghostinspector/test-runner-standalone
