# This is a basic workflow to help you get started with Actions

name: GI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: docker build -t my-app .
      - name: start app and execute Ghost Inspector suite
        env:
          GI_API_KEY: ${{ secrets.GI_API_KEY }}
          GI_SUITE: 5c1d24568ec4123e847a9ecd
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          APP_PORT: 3000
        run: |
          docker network create temp-network
          docker run -d \
            --network temp-network \
            --name my-app \
            my-app
          docker run -d \
            -e GI_API_KEY \
            -e GI_SUITE \
            -e NGROK_TOKEN
            -e my-app:APP_PORT
            --network temp-network \
            ghostinspector/test-runner-standalone
