name: Lighthouse CI for Netlify sites
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Wait for the Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@v1
        id: netlify
        with:
          site_name: "simpixelated"
          max_timeout: 120
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@3.0.0
        with:
          urls: |
            ${{ steps.netlify.outputs.url }}
            ${{ steps.netlify.outputs.url }}/two-year-work-retrospective
          configPath: "./lighthouserc.json"
          temporaryPublicStorage: true
