# This is a basic workflow to help you get started with Actions

name: GI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install, build, and run app
        run: |
          npm install
          npm run build
          npm start &
      - name: test connection
        run: ping -c 4 localhost:3000
      - name: execute Ghost Inspector suite
        env:
          GI_API_KEY: ${{ secrets.GI_API_KEY }}
          GI_SUITE: 5c1d24568ec4123e847a9ecd
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          APP_PORT: 3000
        uses: docker://ghostinspector/test-runner-standalone
